version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:2.257
    ports:
      - "127.0.0.1:7080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    # use named volume in this example for jenkins_home, if you have any issues with bind mount sample, then this is recommended (named mount) and is way more performant

  mails:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "127.0.0.1:7025:8025" # mailhog's web app (think test instance of gmail)
    # - "127.0.0.1:1025:1025" # jenkins will use `mail:1025` to send emails, only map to host if you want to send files

volumes:
  jenkins_home:

# FYI host ports only listening on 127.0.0.1 now, see other compose file for more. 